import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { z } from "zod";
import { Upload, X, Sparkles } from "lucide-react";
import { Database } from "@/integrations/supabase/types";

type ComplaintCategory = Database["public"]["Enums"]["complaint_category"];

const complaintSchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters").max(120, "Title must be less than 120 characters"),
  description: z.string().min(20, "Description must be at least 20 characters").max(5000, "Description must be less than 5000 characters"),
  category: z.string().min(1, "Please select a category"),
});

const categories: ComplaintCategory[] = [
  "Academic",
  "Infrastructure",
  "Hostel",
  "Food",
  "Faculty",
  "Administration",
  "Technical",
  "Other",
];

interface CreateComplaintFormProps {
  userId: string;
  userName: string;
}

export const CreateComplaintForm = ({ userId, userName }: CreateComplaintFormProps) => {
  const [isLoading, setIsLoading] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState<ComplaintCategory | "">("");
  const [markedUrgent, setMarkedUrgent] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<string>("");
  const [attachment, setAttachment] = useState<File | null>(null);
  const navigate = useNavigate();

  const analyzeWithAI = async () => {
    if (!title || !description) {
      toast.error("Please enter title and description first");
      return;
    }

    setIsAnalyzing(true);
    try {
      const { data, error } = await supabase.functions.invoke('analyze-complaint', {
        body: { title, description }
      });

      if (error) throw error;

      setCategory(data.category as ComplaintCategory);
      setAiSuggestion(`AI detected: ${data.category} (${data.sentiment} tone)`);
      toast.success(`AI Suggestion: ${data.category} category`);
    } catch (error: any) {
      console.error('AI analysis error:', error);
      toast.error("AI analysis unavailable, please select category manually");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate file size (10MB max)
      if (file.size > 10 * 1024 * 1024) {
        toast.error("File size must be less than 10MB");
        return;
      }
      // Validate file type
      const allowedTypes = ["image/png", "image/jpeg", "application/pdf"];
      if (!allowedTypes.includes(file.type)) {
        toast.error("Only PNG, JPG, and PDF files are allowed");
        return;
      }
      setAttachment(file);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      complaintSchema.parse({ title, description, category });
      setIsLoading(true);

      // Check for spam using AI
      const { data: spamCheck, error: spamError } = await supabase.functions.invoke('detect-spam-complaint', {
        body: { title, description }
      });

      if (spamError) {
        console.error('Spam detection error:', spamError);
        // Continue even if spam detection fails
      } else if (spamCheck?.is_spam) {
        toast.error(
          `Your complaint appears to be invalid: ${spamCheck.reason}. Please provide meaningful information.`,
          { duration: 6000 }
        );
        setIsLoading(false);
        return;
      }

      let attachmentUrl = null;

      // Upload attachment if provided
      if (attachment) {
        const fileExt = attachment.name.split(".").pop();
        const fileName = `${userId}/${Date.now()}.${fileExt}`;
        
        const { error: uploadError } = await supabase.storage
          .from("complaint-attachments")
          .upload(fileName, attachment);

        if (uploadError) throw uploadError;

        const { data: { publicUrl } } = supabase.storage
          .from("complaint-attachments")
          .getPublicUrl(fileName);

        attachmentUrl = publicUrl;
      }

      // Create complaint with AI-enhanced data
      const { data: complaintData, error: complaintError } = await supabase
        .from("complaints")
        .insert({
          complaint_id: "", // Will be auto-generated by trigger
          student_id: userId,
          student_name: userName,
          title,
          description,
          category: category as ComplaintCategory,
          attachment_url: attachmentUrl,
          marked_urgent: markedUrgent,
          priority: markedUrgent ? 'urgent' : 'medium',
        } as any)
        .select()
        .single();

      if (complaintError) throw complaintError;

      // Create activity log
      await supabase.from("activity_logs").insert({
        complaint_id: complaintData.id,
        action_by: userId,
        action_type: "New Complaint",
        message: `Complaint created: ${title}`,
      });

      toast.success("Complaint submitted successfully!");
      navigate("/student/dashboard");
    } catch (error) {
      if (error instanceof z.ZodError) {
        toast.error(error.errors[0].message);
      } else if (error instanceof Error) {
        toast.error(error.message);
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="shadow-xl border-2">
      <CardHeader className="space-y-3 pb-8">
        <CardTitle className="text-3xl font-bold tracking-tight">Submit New Complaint</CardTitle>
        <CardDescription className="text-base">
          Provide detailed information about your complaint
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title" className="text-base font-medium">Title *</Label>
            <Input
              id="title"
              placeholder="Brief description of your complaint"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              maxLength={120}
              required
              className="h-12 text-base"
            />
            <p className="text-xs text-muted-foreground">{title.length}/120 characters</p>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="category" className="text-base font-medium">Category *</Label>
              <Button 
                type="button" 
                variant="outline" 
                size="sm" 
                onClick={analyzeWithAI}
                disabled={isAnalyzing || !title || !description}
              >
                <Sparkles className="h-4 w-4 mr-2" />
                {isAnalyzing ? "Analyzing..." : "AI Suggest"}
              </Button>
            </div>
            <Select value={category} onValueChange={(value) => setCategory(value as ComplaintCategory)}>
              <SelectTrigger className="h-12 text-base">
                <SelectValue placeholder="Select a category" />
              </SelectTrigger>
              <SelectContent>
                {categories.map((cat) => (
                  <SelectItem key={cat} value={cat}>
                    {cat}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {aiSuggestion && (
              <p className="text-xs text-primary">{aiSuggestion}</p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="description" className="text-base font-medium">Description *</Label>
            <Textarea
              id="description"
              placeholder="Provide detailed information about your complaint..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              maxLength={5000}
              rows={8}
              required
              className="text-base resize-none"
            />
            <p className="text-xs text-muted-foreground">{description.length}/5000 characters</p>
          </div>

          <div className="flex items-center space-x-2">
            <Checkbox 
              id="urgent" 
              checked={markedUrgent}
              onCheckedChange={(checked) => setMarkedUrgent(checked as boolean)}
            />
            <Label 
              htmlFor="urgent" 
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Mark as Urgent (requires immediate attention)
            </Label>
          </div>

          <div className="space-y-2">
            <Label htmlFor="attachment">Attachment (Optional)</Label>
            <div className="flex items-center gap-2">
              {!attachment ? (
                <Label
                  htmlFor="attachment"
                  className="flex items-center gap-2 px-4 py-2 border border-input rounded-md cursor-pointer hover:bg-accent"
                >
                  <Upload className="h-4 w-4" />
                  <span className="text-sm">Upload File</span>
                  <Input
                    id="attachment"
                    type="file"
                    accept=".png,.jpg,.jpeg,.pdf"
                    onChange={handleFileChange}
                    className="hidden"
                  />
                </Label>
              ) : (
                <div className="flex items-center gap-2 px-4 py-2 border border-input rounded-md">
                  <span className="text-sm">{attachment.name}</span>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => setAttachment(null)}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              )}
            </div>
            <p className="text-xs text-muted-foreground">
              Accepted formats: PNG, JPG, PDF (Max 10MB)
            </p>
          </div>

          <div className="flex gap-3 pt-4">
            <Button 
              type="submit" 
              disabled={isLoading}
              size="lg"
              className="flex-1 font-semibold shadow-md hover:shadow-lg transition-all"
            >
              {isLoading ? "Submitting..." : "Submit Complaint"}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/student/dashboard")}
              size="lg"
              className="flex-1 font-semibold hover:bg-accent/5 transition-all"
            >
              Cancel
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
};
